(function(){
var T={"Work":"Trabajo","Services":"Servicios","About":"Sobre mí","Process":"Proceso","Contact":"Contacto","Let's talk":"Hablemos","Menu":"Menú","Close":"Cerrar","Scroll":"Desliza",
"Available for new projects · 2026":"Disponible para nuevos proyectos · 2026","I design":"Diseño experiencias","experiences.":"",
"I'm":"Soy","— a Web Designer and WordPress Developer creating thoughtful digital experiences for businesses, brands and ambitious teams.":"— diseñadora web y desarrolladora WordPress. Creo experiencias digitales cuidadas para empresas, marcas y equipos con ambición.",
"Focus":"Enfoque","Web Design & WordPress":"Diseño web y WordPress","UI / UX Design":"Diseño UI / UX","Brand Identity":"Identidad de marca","Start a project":"Empezar un proyecto","View selected work":"Ver proyectos",
"About my work":"Sobre mi trabajo","I combine design, UX and development to create digital experiences that look":"Combino diseño, UX y desarrollo para crear experiencias digitales que se ven","distinctive":"diferentes","and work beautifully.":"y funcionan de maravilla.",
"Selected work":"Proyectos seleccionados","Recent":"Proyectos","projects":"recientes","Visit website":"Ver web","Case study soon":"Caso de estudio pronto","Screens coming soon":"Capturas próximamente",
"No.":"Nº","Project":"Proyecto","Field":"Sector","Details":"Detalles",
"Interior Design · Web Design":"Interiorismo · Diseño web","Hospitality · Web Design":"Hospitality · Diseño web","Technology · Corporate Website":"Tecnología · Web corporativa","Digital Product · App UX/UI":"Producto digital · App UX/UI","Agritech SaaS · Web Design":"SaaS agritech · Diseño web","NGO · Digital Platform":"ONG · Plataforma digital","Health · Web Design":"Salud · Diseño web","Beauty & Wellness · UI Design":"Belleza y bienestar · Diseño UI","Sports Club · WordPress":"Club deportivo · WordPress","Technology · Web Design":"Tecnología · Diseño web","Food Brand · Web Design":"Marca gastronómica · Diseño web",
"Brand identity and website for a villa rental, with an elegant visual direction aligned with the stay experience.":"Identidad de marca y web para un alquiler de villas, con una dirección visual elegante y alineada con la experiencia de la estancia.",
"Corporate website for an AI retail technology company, explaining a complex product in a clear, structured way.":"Web corporativa para una empresa de tecnología retail con IA, que explica un producto complejo de forma clara y estructurada.",
"Portfolio website for an interior design studio, built to let the projects and imagery lead.":"Web portfolio para un estudio de interiorismo, pensada para que los proyectos y las imágenes sean protagonistas.",
"Website for a beach camp, designed to communicate the experience and make bookings and information easy to find.":"Web para un beach camp, diseñada para transmitir la experiencia y facilitar las reservas y la información.",
"A modern, easy-to-manage website for a sports club, communicating club information, attracting new players and offering a clear experience for families and future academy members. The result is a structured site that makes the most important information easy to reach on desktop and mobile, with a more professional and approachable image aligned with the club’s growth.":"Una web moderna y fácil de gestionar para un club deportivo, que comunica la información del club, capta nuevos jugadores y ofrece una experiencia clara tanto para familias como para futuros integrantes de la academia. Una web estructurada que facilita el acceso a la información más importante en escritorio y móvil, con una imagen más profesional y cercana, alineada con el crecimiento de la entidad.",
"Mobile app design for a municipal digital services platform, focused on simple flows for everyday procedures.":"Diseño de app para una plataforma de servicios municipales digitales, centrada en flujos sencillos para los trámites del día a día.",
"Website for an agritech SaaS product, presenting features and value clearly for a technical audience.":"Web para un producto SaaS agritech, que presenta funcionalidades y valor de forma clara para un público técnico.",
"Digital platform for a social impact organisation, structured to share its mission and engage new members.":"Plataforma digital para una organización de impacto social, estructurada para compartir su misión y atraer nuevos miembros.",
"Website for a health and wellbeing practice, with a warm, discreet tone and clear access to services.":"Web para una consulta de salud y bienestar, con un tono cercano y discreto y acceso claro a los servicios.",
"UI design for a natural beauty and wellness brand, with a clean, calm visual language.":"Diseño UI para una marca de belleza natural y bienestar, con un lenguaje visual limpio y sereno.",
"Website for a craft hot sauce brand, with a bold visual identity and a clear online shop.":"Web para una marca de salsas picantes artesanales, con una identidad visual potente y una tienda online clara.",
"Website for an IT consulting firm, organising services clearly for business clients.":"Web para una consultora IT, que organiza sus servicios de forma clara para clientes empresa.",
"Website for a nutrition and wellbeing professional, designed to explain services and build trust.":"Web para una profesional de la nutrición y el bienestar, diseñada para explicar sus servicios y generar confianza.",
"Web Design":"Diseño web","Information Architecture":"Arquitectura de información","App Design":"Diseño de apps","Prototyping":"Prototipado","UI Design":"Diseño UI","UX/UI Design":"Diseño UX/UI","Responsive Web Design":"Diseño web responsive","Navigation Optimisation":"Optimización de navegación","Content Organisation":"Organización de contenidos",
"What I":"Qué","do":"hago","Product":"Producto","Brand":"Marca",
"Websites that look good, load fast and are easy to manage.":"Webs que se ven bien, cargan rápido y son fáciles de gestionar.","Digital products designed around the people who use them.":"Productos digitales pensados para las personas que los usan.","A clear, consistent identity across every touchpoint.":"Una identidad clara y coherente en cada punto de contacto.",
"Modern, conversion-focused websites designed around your brand, audience and goals.":"Webs modernas y orientadas a conversión, diseñadas en torno a tu marca, tu público y tus objetivos.",
"WordPress Development":"Desarrollo WordPress","Custom WordPress websites using Elementor Pro, responsive development, custom CSS and JavaScript.":"Webs WordPress a medida con Elementor Pro, desarrollo responsive y CSS y JavaScript personalizados.",
"Website Redesign":"Rediseño web","Transforming outdated websites into modern, responsive and visually engaging digital experiences.":"Transformo webs anticuadas en experiencias digitales modernas, responsive y atractivas.",
"Website Support":"Mantenimiento web","Ongoing improvements, responsive fixes, performance optimisation and new functionality.":"Mejoras continuas, ajustes responsive, optimización del rendimiento y nuevas funcionalidades.",
"Interfaces, user flows, wireframes and high-fidelity designs created in Figma.":"Interfaces, flujos de usuario, wireframes y diseños de alta fidelidad en Figma.",
"Mobile and web app interfaces designed for clarity and ease of use.":"Interfaces de apps móviles y web pensadas para ser claras y fáciles de usar.",
"Wireframes & Prototypes":"Wireframes y prototipos","Interactive prototypes to test flows and ideas before development.":"Prototipos interactivos para validar flujos e ideas antes de desarrollar.",
"Design Systems":"Sistemas de diseño","Reusable components and style guides that keep products consistent.":"Componentes reutilizables y guías de estilo que mantienen la coherencia del producto.",
"UX Audit":"Auditoría UX","Reviewing existing products to find friction and improve usability.":"Reviso productos existentes para detectar fricciones y mejorar la usabilidad.",
"Logos, visual identity systems and brand guidelines that give businesses a clear, consistent presence.":"Logotipos, sistemas de identidad visual y manuales de marca que dan a las empresas una presencia clara y coherente.",
"Graphic & Digital Documents":"Diseño gráfico y documentos digitales","Graphic design, presentations, brochures, editorial layouts and digital documents aligned with the brand.":"Diseño gráfico, presentaciones, folletos, maquetación editorial y documentos digitales alineados con la marca.",
"Based in Spain · Working worldwide":"Desde España · Trabajo en todo el mundo",
"I'm Elena, a Web Designer and WordPress Developer with a background in":"Soy Elena, diseñadora web y desarrolladora WordPress con formación en","Industrial Design Engineering":"Ingeniería en Diseño Industrial","and Product Development.":"y Desarrollo de Producto.",
"My engineering background shaped the way I work: I start by understanding how things function — the business, the people who use it and what it needs to achieve — and only then move into design. That mix of structure and aesthetics is what I bring to every project.":"Mi formación en ingeniería ha marcado mi forma de trabajar: primero entiendo cómo funcionan las cosas (el negocio, las personas que lo usan y lo que necesita conseguir) y solo después paso al diseño. Esa mezcla de estructura y estética es lo que aporto a cada proyecto.",
"For more than 6 years I've designed and built websites, apps, brand identities and digital documents for architecture and interior studios, hospitality brands, health and wellness businesses, technology companies, NGOs and sports clubs, working with clients in Spain and abroad.":"Desde hace más de 6 años diseño y desarrollo webs, apps, identidades de marca y documentos digitales para estudios de arquitectura e interiorismo, marcas de hospitality, negocios de salud y bienestar, empresas tecnológicas, ONG y clubes deportivos, con clientes en España y en el extranjero.",
"I handle the whole process myself, from strategy and UX to visual design, WordPress development and SEO On-Page. That means one point of contact, clear communication and a result that looks good and is easy to manage once it's live.":"Me encargo de todo el proceso, desde la estrategia y la UX hasta el diseño visual, el desarrollo en WordPress y el SEO On-Page. Eso significa un único punto de contacto, una comunicación clara y un resultado que se ve bien y es fácil de gestionar una vez publicado.",
"Years experience":"Años de experiencia","Projects":"Proyectos","Clients":"Clientes","Responsive Design":"Diseño responsive","Graphic Design":"Diseño gráfico","Digital Documents":"Documentos digitales","Presentations":"Presentaciones",
"How we":"Cómo","work":"trabajo","Discover":"Descubrir","Understanding the business, audience and objectives.":"Entender el negocio, el público y los objetivos.","Design":"Diseñar","Creating the visual direction, structure and user experience.":"Crear la dirección visual, la estructura y la experiencia de usuario.","Build":"Desarrollar","Developing with WordPress, Elementor and custom code where needed.":"Desarrollo con WordPress, Elementor y código a medida cuando hace falta.","Refine":"Pulir","Testing, responsive optimisation and final details.":"Pruebas, optimización responsive y detalles finales.","Launch":"Lanzar","Publishing the website and making sure everything is ready.":"Publicar la web y comprobar que todo está listo.",
"Let's make":"Hagamos","something":"algo","great.":"grande.","Have a project in mind? Tell me about it — I usually reply within 48 hours.":"¿Tienes un proyecto en mente? Cuéntamelo; suelo responder en menos de 48 horas.","Email copied":"Email copiado",
"© 2026 Elena García · Web Designer · UI/UX · WordPress":"© 2026 Elena García · Diseñadora web · UI/UX · WordPress","Back to top ↑":"Volver arriba ↑",
"Name":"Nombre","Phone":"Teléfono","I need":"Necesito","Graphic design":"Diseño gráfico","Project description":"Descripción del proyecto","Send request":"Enviar solicitud"};
var d=document,root=d.documentElement,nodes=[],dataEs=[].slice.call(d.querySelectorAll('[data-es]'));
dataEs.forEach(function(el){el.dataset.en=el.innerHTML});
var w=d.createTreeWalker(d.body,NodeFilter.SHOW_TEXT,{acceptNode:function(n){var p=n.parentNode;if(!n.nodeValue.trim()||p.closest('script,style,[data-es],.dgs,.stat__n'))return NodeFilter.FILTER_REJECT;return T[n.nodeValue.trim()]!==undefined?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});
while(w.nextNode())nodes.push([w.currentNode,w.currentNode.nodeValue]);
var ta=d.querySelector('textarea[name=message]'),taEn=ta&&ta.placeholder;
function letters(word){return word.split('').map(function(c,i){return '<span style="--i:'+i+'">'+c+'</span>'}).join('')}
function set(l){root.lang=l;
nodes.forEach(function(x){var en=x[1],k=en.trim();x[0].nodeValue=l==='es'?en.replace(k,T[k]):en});
dataEs.forEach(function(el){el.innerHTML=l==='es'?el.dataset.es:el.dataset.en;if(el.classList.contains('sec-h')&&!el.querySelector('.ln')){var s=d.createElement('span');s.className='ln';while(el.firstChild)s.appendChild(el.firstChild);el.appendChild(s)}});
if(ta)ta.placeholder=l==='es'?'Qué necesitas, plazos, presupuesto…':taEn;
d.querySelectorAll('.dgs__i').forEach(function(i){i.innerHTML=letters(l==='es'?'digitales':'digital')});
d.querySelectorAll('.lang button').forEach(function(b){b.classList.toggle('on',b.dataset.lang===l)});
dispatchEvent(new Event('resize'))}
d.querySelectorAll('.lang button').forEach(function(b){b.addEventListener('click',function(){set(b.dataset.lang)})});
})();
